# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: callahanrts
email: callahanrts@gmail.com
image: "/assets/profile2.jpg"
profile_image: "/assets/profile2.jpg"
author: Cody
defaults:
  - scope:
      path: ""
    values:
      image: /assets/profile2.jpg

description: > # this means to ignore newlines until "baseurl:"
  Cody Callahan - Software Developer
#  Cody Callahan is an experienced software engineer in the Reno, Nevada area. He has
#  5+ years experience working in full stack web development. Cody is well versed in
#  Ruby on Rails, as well as a multitude of front end frameworks such as angularjs and
#  knockoutjs. With experience with docker and various dev ops utilities, he can see
#  applications from development to deployment.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codycallahan.com" # the base hostname & protocol for your site, e.g. http://example.com

# navigation:
#   - Blog
#   - Projects
#   - About

#twitter_username: jekyllrb
github_username:  callahanrts
permalink: /blog/:title
google_analytics: UA-26799060-1

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - node_modules - Gemfile
  - Gemfile.lock

plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

disqus:
  shortname: callahanrts

minima:
    date_format: "%b %d, %Y"
